"""Poltrona Libera — second generation creatives: a funnel per audience, and visibly different styles
(photo-dark, typographic-cream, ink-with-big-number, split photo/text, photo carousel cards).
Run after make_creatives_poltrona.py: python -m scripts.make_creatives_poltrona2"""
from __future__ import annotations

import os

from PIL import Image, ImageDraw, ImageFont

from scripts.make_creatives_poltrona import ACC, INK, OUT, PAPER, PUB, SANS, SANS_B, SERIF_B, SERIF_I, SIZES, F, ad_photo, ad_typo, brand_bar, draw_lines, photo_bg, wrap

P = lambda n: f"{PUB}/postazione_{n}.jpg"


def ad_ink_number(number, headline, sub, kicker, size_key, cta="Guarda le postazioni →"):
    """Dark ink background, one huge terracotta numeral: unmistakably different from the photo and cream ads."""
    w, h = SIZES[size_key]; im = Image.new("RGB", (w, h), INK); d = ImageDraw.Draw(im); s = w / 1080
    d.text((72, 84), kicker, font=F(SANS_B, int(28 * s)), fill=(200, 190, 175))
    d.text((60, h * 0.16), number, font=F(SERIF_B, int(330 * s)), fill=ACC)
    y = h * 0.16 + int(360 * s)
    y = draw_lines(d, 72, y, wrap(d, headline, F(SERIF_B, int(78 * s)), w - 144), F(SERIF_B, int(78 * s)), PAPER, int(88 * s))
    y = draw_lines(d, 72, y + 16, wrap(d, sub, F(SANS, int(36 * s)), w - 160), F(SANS, int(36 * s)), (210, 200, 188), int(48 * s))
    y = min(y, h - int(250 * s))
    d.rounded_rectangle((72, y + 30, 72 + int(520 * s), y + 30 + int(92 * s)), radius=999, fill=PAPER)
    d.text((72 + int(48 * s), y + 30 + int(22 * s)), cta, font=F(SANS_B, int(34 * s)), fill=INK)
    brand_bar(d, w, h, True)
    return im


def ad_split(photo, headline, sub, offer_line, size_key, cta="Guarda le postazioni →"):
    """Photo on top half, cream text block below with a terracotta offer chip."""
    w, h = SIZES[size_key]; im = Image.new("RGB", (w, h), PAPER); s = w / 1080
    ph_h = int(h * 0.46); im.paste(photo_bg(photo, (w, ph_h), 0.08), (0, 0)); d = ImageDraw.Draw(im)
    chip = offer_line; cw = int(d.textlength(chip, font=F(SANS_B, int(30 * s))) + 64)
    d.rounded_rectangle((72, ph_h - int(34 * s), 72 + cw, ph_h + int(34 * s)), radius=999, fill=ACC)
    d.text((72 + 32, ph_h - int(16 * s)), chip, font=F(SANS_B, int(30 * s)), fill=PAPER)
    y = ph_h + int(70 * s)
    y = draw_lines(d, 72, y, wrap(d, headline, F(SERIF_B, int(76 * s)), w - 144), F(SERIF_B, int(76 * s)), INK, int(86 * s))
    y = draw_lines(d, 72, y + 14, wrap(d, sub, F(SANS, int(36 * s)), w - 160), F(SANS, int(36 * s)), (63, 58, 53), int(48 * s))
    y = min(y, h - int(250 * s))
    d.rounded_rectangle((72, y + 26, 72 + int(520 * s), y + 26 + int(92 * s)), radius=999, fill=INK)
    d.text((72 + int(48 * s), y + 26 + int(22 * s)), cta, font=F(SANS_B, int(34 * s)), fill=PAPER)
    brand_bar(d, w, h, False)
    return im


def photo_card(photo, n, title, text):
    w = h = 1080; im = photo_bg(photo, (w, h), 0.55); d = ImageDraw.Draw(im)
    d.ellipse((72, 72, 168, 168), fill=ACC); d.text((102, 88), str(n), font=F(SERIF_B, 56), fill=PAPER)
    y = 560
    y = draw_lines(d, 72, y, wrap(d, title, F(SERIF_B, 74), w - 144), F(SERIF_B, 74), PAPER, 86)
    draw_lines(d, 72, y + 20, wrap(d, text, F(SANS, 38), w - 144), F(SANS, 38), (225, 218, 206), 50)
    brand_bar(d, w, h, True)
    return im


def main():
    os.makedirs(OUT, exist_ok=True)
    # ---- owners: replace 'gestito' with the ink-number style (the other two stay: photo-dark and cream-typo) ----
    for k in SIZES:
        ad_ink_number("15%", "Solo quando la postazione rende.", "Nessun costo fisso. Selezione, contratto, SCIA e incasso li facciamo noi; se la professionista lascia, la sostituiamo.", "PER TITOLARI DI SALONE · MILANO", k, "Affitta la tua postazione →").save(f"{OUT}/gestito_{k}.png")
    # ---- professionals: 4 distinct ads ----
    for k in SIZES:
        ad_photo("prof_libera", f"{PUB}/salone_2.jpg", "Lavora in proprio, senza aprire un salone.", "Postazioni in saloni veri di Milano da 400 € al mese. Orari tuoi, incasso tuo. Guardi, visiti, poi decidi.", "MILANO · POSTAZIONI", k).save(f"{OUT}/prof_libera_{k}.png")
        ad_ink_number("100%", "Di quello che incassi, tuo.", "Non il 40% di uno stipendio. Contratto a norma, mese di prova, aiuto per aprire l'impresa.", "PER PARRUCCHIERE E BARBIERI · MILANO", k).save(f"{OUT}/prof_cento_{k}.png")
        ad_split(P(2), "Le prime 30 non pagano l'attivazione.", "99 € di contratto, SCIA e registrazione azzerati per le prime 30 professioniste iscritte a Milano. Poi solo il canone.", "OFFERTA DI LANCIO · MILANO", k).save(f"{OUT}/prof_offerta_{k}.png")
    # domicilio (cream typographic) already generated by make_creatives_poltrona.py
    # ---- professionals carousel: 3 steps with photos ----
    steps = [(P(1), 1, "Guardi gli annunci", "Foto, zona, giorni e canone di ogni postazione a Milano."),
             (P(3), 2, "Visiti il salone", "Chiedi il contatto e incontri la titolare. Gratis, senza impegno."),
             (P(2), 3, "Firmi e lavori", "Contratto a norma preparato da noi. Da quel giorno la poltrona è tua.")]
    for photo, n, t, x in steps:
        photo_card(photo, n, t, x).save(f"{OUT}/carousel_prof_{n}.png")
    print("ok", sorted(f for f in os.listdir(OUT) if f.startswith(("prof_", "carousel_prof", "gestito"))))


if __name__ == "__main__":
    main()
