# -*- coding: utf-8 -*-
"""Editorial plan for the Poltrona Libera Facebook page: first month, written by hand (no LLM on public copy).
Three posts a week (Tue/Thu/Sat 12:30 Rome), alternating the two audiences; real listings are posted automatically
when approved (app.services.social.enqueue_listing). Images are generated by scripts/make_social_images.py into
public/poltrona/social/ and served from poltronalibera.it."""

SITE = "https://poltronalibera.it"
OWNERS = f"{SITE}/lp/poltrona_libera_titolari"
PROS = f"{SITE}/lp/poltrona_libera_professioniste"
CATALOG = f"{SITE}/pl/postazioni"
WA = "392 590 9721"

# (slug, audience, image headline, image accent word, post text)
POSTS = [
    ("apertura", "entrambi", "La poltrona vuota del tuo salone.", "vuota",
     "Poltrona Libera nasce da una cosa che ci hanno detto le titolari di salone: «non trovo personale», «la dipendente è andata via».\n\n"
     "Dall'altra parte ci sono parrucchiere e barbieri che vogliono lavorare in proprio senza aprire un salone.\n\n"
     "Noi facciamo una cosa sola: i saloni pubblicano la postazione libera (gratis), le professioniste la vedono e chiamano direttamente. Poi vi accordate tra di voi.\n\n"
     f"Hai una poltrona libera? 👉 {OWNERS}\nCerchi una postazione? 👉 {PROS}"),
    ("non_trovo", "titolari", "«Non trovo personale.»", "personale",
     "È la frase che sentiamo più spesso dalle titolari. Prima del 2020 bastava un foglio in vetrina; oggi chi esce dalle scuole ha quattro strade e il salone è solo una.\n\n"
     "C'è un'alternativa all'assumere: affittare la postazione a una professionista in proprio, che porta le sue clienti e paga un canone (a Milano 350-1.200 € al mese).\n\n"
     f"Pubblicare la postazione su Poltrona Libera è gratis e ci vogliono cinque minuti. 👉 {OWNERS}\n\nDubbi? Scrivimi su WhatsApp al {WA}, rispondo io, Giovanni."),
    ("in_proprio", "professioniste", "Lavora in proprio, senza aprire un salone.", "in proprio",
     "Aprire un salone vuol dire affitto, attrezzature, fideiussioni. Affittare una poltrona vuol dire una postazione vera in un salone vero, con i tuoi orari e le tue clienti.\n\n"
     "Su Poltrona Libera vedi le postazioni disponibili a Milano con zona, giorni, prezzo, foto e il numero della titolare. Chiami tu, direttamente. Gratis.\n\n"
     f"👉 {CATALOG}"),
    ("legale", "titolari", "È legale? Sì, dal 2012.", "legale",
     "«Ma l'affitto di poltrona è legale?» Sì: in Italia dal 2012 (accordo nazionale delle categorie artigiane) e a Milano è regolato dalla delibera comunale 120/2018.\n\n"
     "Le regole in breve: chi affitta deve essere un'impresa artigiana con P.IVA; lavora con i suoi orari e le sue clienti; serve un contratto scritto e registrato. Puoi affittare 1 postazione fino a 3 dipendenti, 2 da 4 a 9, 3 oltre i 10.\n\n"
     f"Il resto lo decidete voi. Pubblica la postazione, gratis: {OWNERS}"),
    ("clienti", "professioniste", "Le tue clienti restano tue.", "tue",
     "Lavorare in una postazione in affitto non vuol dire regalare le clienti al salone: come gestirle lo decidete voi due, per iscritto, prima di iniziare. Ognuna con le proprie, oppure condivise con regole chiare.\n\n"
     "Le postazioni online a Milano, con il numero della titolare: 👉 " + CATALOG),
    ("andata_via", "titolari", "«La dipendente è andata via.»", "andata via",
     "Succede, e succede nel momento peggiore. Nelle prime 48 ore le cose che contano sono due: scrivere alle sue clienti abituali, una per una, e non lasciare la postazione vuota.\n\n"
     "Per la postazione: pubblicala su Poltrona Libera. Le professioniste di Milano la vedono con giorni, prezzo e foto, e ti chiamano. Gratis.\n\n"
     f"👉 {OWNERS}"),
    ("quanto", "titolari", "Quanto vale una postazione a Milano?", "vale",
     "Le cifre che vediamo negli annunci: 350-500 € al mese in periferia, 500-700 in semicentro, 700-1.200 in centro, per una postazione a tempo pieno. Oppure una percentuale sugli incassi (30-50%), o una formula mista.\n\n"
     "Sei mesi vuota sono 3.000-6.000 € che non entrano. Pubblicare l'annuncio costa cinque minuti e niente.\n\n"
     f"👉 {OWNERS}"),
    ("domicilio", "professioniste", "Lavori a domicilio? Prenditi un indirizzo.", "indirizzo",
     "Chi lavora a domicilio lo sa: lavatesta della cliente, luce sbagliata, la borsa sempre in macchina. Una postazione in un salone vero costa da 300-400 € al mese per 2-3 giorni a settimana e ti dà un posto dove le clienti vengono da te.\n\n"
     f"Guarda le postazioni disponibili a Milano: {CATALOG}"),
    ("come_funziona_t", "titolari", "Cinque minuti. Poi ti chiamano.", "chiamano",
     "Come funziona per un salone, in tre passi:\n1. Pubblichi la postazione: zona, giorni, prezzo, cosa è incluso, una foto, il numero.\n2. La controlliamo e va online in giornata.\n3. Le professioniste ti chiamano direttamente. Vi accordate tra di voi.\n\n"
     f"Nessun costo, nessuna commissione. 👉 {OWNERS}"),
    ("part_time", "professioniste", "Anche solo tre giorni a settimana.", "tre giorni",
     "Molti saloni offrono postazioni part-time: giovedì-sabato, o martedì e venerdì. Perfetto per chi parte in proprio e vuole tenere anche le clienti a domicilio, o per chi ha una famiglia.\n\n"
     f"Negli annunci trovi i giorni disponibili. Guarda: {CATALOG}"),
    ("stanca", "titolari", "Stanca di dipendenti?", "dipendenti",
     "Buste paga, ferie, malattie, preavvisi. Un titolare ci ha scritto: «si è licenziato, e ora non voglio più personale».\n\n"
     "La postazione vuota può pagarti un canone ogni mese invece di costarti una busta paga. Si chiama affitto di poltrona, ed è il motivo per cui esiste Poltrona Libera.\n\n"
     f"Pubblica la postazione, gratis: {OWNERS}"),
    ("chiama", "professioniste", "Vedi il numero. Chiami tu.", "Chiami tu",
     "Su Poltrona Libera non ci sono moduli in mezzo: ogni annuncio ha il nome del salone, la zona, i giorni, il prezzo, le foto e il numero della titolare. Ti piace? La chiami, vai a vedere, decidi.\n\n"
     f"Gratis, sempre. 👉 {CATALOG}"),
]
